Import("env")
Import("tag")
def make_objs(file_list, suffix, enviroment) :
    return [ enviroment.Object(file + '-' + suffix + '.o', file + '.cpp' ) for file in file_list ]

files = Split(' tomasulo/inst_buffer_row tomasulo/inst_buffer tomasulo/reg_board tomasulo/rob.cpp')
objs = make_objs(files, tag, env)
Return('objs')
