Import("env")
Import("tag")
def make_objs(file_list, suffix, enviroment) :
    return [ enviroment.Object(file + '-' + suffix + '.o', file + '.cpp' ) for file in file_list ]

files = Split(' memory/cache memory/main_memory tomasulo/tomasulo tomasulo/instruction tomasulo/inst_buffer tomasulo/rob tomasulo/reservation_station ' +
               'tomasulo/statics ')
objs = make_objs(files, tag, env)
Return('objs')
